---
- name: install rabbitmq-server
  shell: export RABBITMQ_NODE_IP_ADDRESS={{ internal_ip }}; apt-get -y install rabbitmq-server;

- name: stop rabbitmq-server
  service: name=rabbitmq-server
           state=stopped

- name: update .erlang.cookie
  template: src=.erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie
        group=rabbitmq
        owner=rabbitmq
        mode=0400
  when: ERLANG_TOKEN is defined

- name: copy rabbitmq config file
  template: src=rabbitmq-env.conf dest=/etc/rabbitmq/rabbitmq-env.conf 
        group=rabbitmq
        owner=rabbitmq
        mode=0744

- name: start and enable rabbitmq-server
  service: name=rabbitmq-server
           state=started
           enabled=yes

- name: modify rabbitmq password
  command: rabbitmqctl change_password guest {{ RABBIT_PASS }}
  when: "RABBIT_USER is defined and RABBIT_USER == 'guest'"
  ignore_errors: True

- name: add rabbitmq user
  command: rabbitmqctl add_user {{ RABBIT_USER }} {{ RABBIT_PASS }}
  when: "RABBIT_USER is defined and RABBIT_USER != 'guest'"
  ignore_errors: True

- name: set rabbitmq user permission
  command: rabbitmqctl set_permissions -p / {{ RABBIT_USER }} ".*" ".*" ".*"
  when: "RABBIT_USER is defined and RABBIT_USER != 'guest'"

