---
- name: create rabbitmq directory
  file: path=/etc/rabbitmq state=directory mode=0755

- name: copy rabbitmq config file
  template: src=rabbitmq-env.conf dest=/etc/rabbitmq/rabbitmq-env.conf mode=0755
