---
- name: update .erlang.cookie
  copy: src=.erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie
        group = rabbitmq
        owner = rabbitmq
        mode 0400

- name: stop rabbitmq app
  command: rabbitmqctl stop_app
  ignore_errors: yes

- name: join  cluster
  command: rabbitmqctl join_cluster rabbit@{{ item }}
  when: item  != inventory_hostname
  with_items:
    groups['controller']

- name: start rabbitmq app
  command: rabbitmqctl start_app

- name: set the HA policy
  rabbitmq_policy: name=ha-all pattern='^(?!amq\.).*' tags="ha-mode=all"

