---
- name: install keepalived
  apt: name=keepalived state=present

- name: install xinetd
  apt: name=xinetd state=present

- name: install haproxy
  apt: name=haproxy state=present

- name: activate ip_nonlocal_bind
  sysctl: name=net.ipv4.ip_nonlocal_bind value=1
          state=present reload=yes

- name: update haproxy cfg
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: set haproxy enable flag
  lineinfile: dest=/etc/default/haproxy state=present
              regexp="ENABLED=*"
              line="ENABLED=1"
  notify: restart haproxy

- name: set haproxy log
  lineinfile: dest=/etc/rsyslog.conf state=absent
              regexp="local0.* /var/log/haproxy.log"

- name: set haproxy log
  lineinfile: dest=/etc/rsyslog.conf state=present
              line="local1.* /var/log/haproxy.log"
  notify: restart rsyslog

- name: copy galera_chk file
  copy: src=galera_chk dest=/usr/local/bin/galera_chk mode=0777

- name: add network service
  lineinfile: dest=/etc/services state=present
              line="mysqlchk          9200/tcp"
              insertafter="Local services"
  notify: restart xinetd

- name: copy mysqlchk file
  copy: src=mysqlchk dest=/etc/xinetd.d/mysqlchk mode=0777
  notify: restart xinetd

- name: set keepalived log
  lineinfile: dest=/etc/rsyslog.conf state=absent
              regexp="local0.*  /var/log/keepalived.log"

- name: set keepalived log
  lineinfile: dest=/etc/rsyslog.conf state=present
              line="local0.*  /var/log/keepalived.log"
  notify: restart rsyslog

- name: update keepalived info
  template: src=keepalived.conf dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived
