---
# keystone
- name: create keystone db model
  mysql_db: name=keystone
            state=present

- name: create keystone user
  mysql_user: host={{ item }}
              name=keystone
              password={{ KEYSTONE_DBPASS }}
              priv=keystone.*:ALL
              state=present
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

# glance
- name: create glance database
  mysql_db: name=glance
            state=present

- name: create glance user
  mysql_user: host={{ item }}
              name=glance
              password={{ GLANCE_DBPASS }}
              priv=glance.*:ALL
              state=present
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

# neutron
- name: create neutron database
  mysql_db: name=neutron
            state=present

- name: create neutron remote user
  mysql_user: host={{ item }}
              name=neutron
              password={{ NEUTRON_DBPASS }}
              priv=neutron.*:ALL
              state=present
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

# ovs_neutron
- name: create ovs_neutron database
  mysql_db: name=ovs_neutron
            state=present

- name: grant access to ovs_neutron
  mysql_user: host=%
              name=neutron
              password={{ NEUTRON_DBPASS }}
              priv=ovs_neutron.*:ALL
              state=present
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

# nova
- name: create nova database
  mysql_db: name=nova
            state=present

- name: create nova user
  mysql_user: host={{ item }}
              name=nova
              password={{ NOVA_DBPASS }}
              priv=nova.*:ALL
              state=present
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

# cinder
- name: create cinder database
  mysql_db: name=cinder
            state=present

- name: create cinder user
  mysql_user: host={{ item }}
              name=cinder
              password={{ CINDER_DBPASS }}
              priv=cinder.*:ALL
              state=present
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

- name: create wsrep sst user
  mysql_user: name={{ WSREP_SST_USER }}
              host={{ item }}
              password={{ WSREP_SST_PASS }}
              priv=ALL.*:ALL
              state=present
  when: "ha is defined and HA_CLUSTER[inventory_hostname] == None"
  with_items:
     - "localhost"
     - "%"
     - "{{ inventory_hostname }}"

- name: reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
