---
- name: install python-mysqldb
  apt: name={{ item }} state=present force=yes
  with_items:
      - libaio1
      - libssl0.9.8
      - mysql-client-5.5
      - python-mysqldb

- name: download mariadb and galera deb package
  get_url: url={{ item.url }} dest=/opt/{{ item.filename }}
  with_items:
    - { url:  "{{ MARIADB_URL }}", filename: "{{ MARIADB }}" }
    - { url:  "{{ GALERA_URL }}", filename: "{{ GALERA }}" }

- name: install mariadb  and galera packages
  command: dpkg -i /opt/{{ item }}
  with_items:
    - "{{ MARIADB }}"
    - "{{ GALERA }}"

- name: update mariadb my.cnf
  template: src=my.cnf dest=/etc/mysql/my.cnf backup=yes

- name: update galera wsrep.cnf
  template: src=wsrep.cnf dest=/etc/mysql/conf.d/wsrep.cnf backup=yes

- name: update wsrep_cluster_address
  lineinfile: dest=/etc/mysql/conf.d/wsrep.cnf state=present regexp="^#wsrep_cluster_address=*"
              line="wsrep_cluster_address=gcomm://{{ HA_CLUSTER[inventory_hostname] }}" backup=yes

- name: update wsrep_sst_rsync uid 
  lineinfile: dest=/usr/bin/wsrep_sst_rsync state=absent regexp="\s*uid = \$MYUID$"  backup=yes

- name: update wsrep_sst_rsync gid 
  lineinfile: dest=/usr/bin/wsrep_sst_rsync state=absent regexp="\s*gid = \$MYGID$"  backup=yes

- name: manually restart mysql server
  service: name=mysql
           state=restarted

- include: data.yml
  when: HA_CLUSTER[inventory_hostname] == None
