---
- name: install python-mysqldb
  apt: name={{ item }} state=present
  with_items:
      - python-mysqldb

- name: download mariadb and galera deb package
  get_url: url={{ item.url }} dest=/opt/{{ item.filename }}
  with_items:
    - { url:  "{{ MARIADB_URL }}", filename: "{{ MARIADB }}" }
    - { url:  "{{ GALERA_URL }}", filename: "{{ GALERA }}" } 

- name: install mariadb  and galera packages
  apt: deb=/opt/{{ item }} state=installed
  with_items:
    - "{{ MARIADB }}" 
    - "{{ GALERA }}" 

- name: update mariadb my.cnf
  copy: src=my.cnf dest=/etc/mysql/my.cnf backup=yes

- name: update galera wsrep.cnf
  template: src=wsrep.cnf dest=/etc/mysql/conf.d/wsrep.cnf

- name: update wsrep_cluster_address
  lineinfile: dest=/etc/mysql/conf.d/wsrep.cnf state=present regexp="^#wsrep_cluster_address=*" 
              line="wsrep_cluster_address=gcomm://{{ cluster[inventory_hostname] }}"

- name: manually restart mysql server
  service: name=mysql
           state=restarted

- name: init database root password with NULL
  shell: mysqladmin -uroot -proot password ""
  ignore_errors: yes
 
      
- name: create wsrep sst local user
  mysql_user: name={{ WSRET_SST_USER }}
              password={{ WSRET_SST_PASS }}
              priv=ALL.*:ALL
              state=present

- name: create wsrep sst local user
  mysql_user: name={{ WSRET_SST_USER }}
              host=%
              password={{ WSRET_SST_PASS }}
              priv=ALL.*:ALL
              state=present
