---
- name: install mysql client and server packages
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - mysql-server

- name: update mysql my.cnf
  copy: src=my.cnf
        dest=/etc/mysql/my.cnf
        backup=yes
  notify:
    - restart mysql

- name: manually restart mysql server
  service: name=mysql
           state=restarted

