---
- hosts: all
  remote_user: root
  sudo: true
  roles:
    - repo

- hosts: ha
  remote_user: root
  sudo: True
  roles:
    - ha

- hosts: controller
  remote_user: root
  sudo: True
  roles:
      - common
      - database
      - mq
      - keystone
      - nova-controller
      - neutron-controller
      - dashboard
      - cinder-controller
      - glance

- hosts: compute
  remote_user: root
  sudo: True
  roles:
    - common
    - nova-compute
    - neutron-compute

