---
- hosts: all
  remote_user: root
  sudo: true
  roles:
    - repo
    - common

- hosts: ha
  remote_user: root
  sudo: True
  roles:
    - ha

- hosts: controller
  remote_user: root
  sudo: True
  roles:
      - database
      - mq
      - keystone
      - nova-controller
      - neutron-controller
      - dashboard
      - cinder-controller
      - glance
      - cinder-volume
      - neutron-common
      - neutron-network
      - odl-os-cluster

- hosts: compute
  remote_user: root
  sudo: True
  roles:
    - nova-compute
    - neutron-compute

